In [55]:
# importando bibliotecas
import time
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Categoria - Livros

In [58]:
#declarando variáveis cards
cards = []

for i in range(12):
    time.sleep(10)
    url = 'https://www.magazineluiza.com.br/busca/livros%20de%20fic%C3%A7%C3%A3o/?page=' + str(i + 1) + '&sortOrientation=desc&sortType=soldQuantity'
    headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'}
    response = requests.get(url, headers = headers)
    soup = BeautifulSoup(response.content, "html.parser")

    anuncios = soup.find('ul', class_="sc-iktFfs ekIdSn sc-irlQje gbimYp sc-fBxREx fjFlfr").findAll('li', class_="sc-eCVOVf loRbcV")
    
    #Obtendo as informações dos cards
    for anuncio in anuncios:
        card = {}

        #nome do livro
        nome = anuncio.find('h2', class_="sc-bHXGc hsFKpx")
        try:
            card['Livro'] = nome.getText().split('-', 1)[1]
        except IndexError:
            card['Livro'] = nome.getText()

        #preco do livro
        try:
            card['preco'] = anuncio.find('p').getText().replace('\xa0', ' ').split()[1]
        except AttributeError:
            card['preco'] = 0

        #preco com desconto
        try:
            card['preco_desconto'] = anuncio.find('p', class_="sc-hKgJUU kegCEa sc-bxnjHY cTpdOW").getText().replace('\xa0', ' ').split()[1]
        except AttributeError:
            card['preco_desconto'] = 0
        
#         card['preco_desconto'] = anuncio.find('p', class_="sc-hKgJUU kegCEa sc-bxnjHY cTpdOW").getText()

        #capiturando o preco parcelaado
        try:
            value = anuncio.find('div', class_="sc-jSgvzq fdbhJo sc-kGNyvp kBUBND").findAll('p')[2].getText().split()[1:5:3]   
            card['parcelas'] = value[0].split('x')[0]
            card['valor_parcela'] = value[1]
        except IndexError:
            card['parcelas'] = 1
            card['valor_parcela'] = card['preco_desconto']
        except AttributeError:
            card['parcelas'] = "0"
            card['valor_parcela'] = 0

        #Adicionando resultado a lista cards
        cards.append(card)
    
#Criando um dataframe com os resultados
dataset = pd.DataFrame(cards)
dataset.to_csv('./livros_magalu.csv', sep=';', index = False, encoding = 'utf-8-sig')
dataset

,Livro,preco,preco_desconto,parcelas,valor_parcela
0,A garota do lago,"39,90","8,40",1,"8,40"
1,BOX HARRY POTTER EDIÇÃO COMEMORATIVA 20 ANOS ...,"499,90","237,41",12,"20,83"
2,Box Trilogia O Senhor dos Anéis,"199,90","98,00",6,"16,33"
3,As crônicas de Nárnia - volume único,"99,90","29,90",1,"29,90"
4,O pequeno príncipe,"21,90","10,70",1,"10,70"
...,...,...,...,...,...
710,coleção ii,"49,90","32,90",1,"32,90"
711,Inferno (Ilustrado),"69,90","69,90",1,"69,90"
712,Inimigos públicos,"41,08","41,08",1,"41,08"
713,Quadribol através dos séculos,"44,90","40,41",1,"40,41"
714,Os demônios de Deus,"34,70","34,70",1,"34,70"

# Categoria - Geladeira

In [64]:
#declarando variáveis cards
cards = []

for i in range(12):
    time.sleep(10)
    url = f'https://www.magazineluiza.com.br/busca/geladeira/?page={i + 1}&sortOrientation=desc&sortType=soldQuantity'
    headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'}
    response = requests.get(url, headers = headers)
    soup = BeautifulSoup(response.content, "html.parser")

    anuncios = soup.find('ul', class_="sc-iktFfs ekIdSn sc-irlQje gbimYp sc-fBxREx fjFlfr").findAll('li', class_="sc-eCVOVf loRbcV")
    
    #Obtendo as informações dos cards
    for anuncio in anuncios:
        card = {}

        #nome da geladeira
        nome = anuncio.find('h2', class_="sc-bHXGc hsFKpx")
        card['Geladeira'] = nome.getText()

        #preco da geladeira
        try:
            card['preco'] = anuncio.find('p').getText().replace('\xa0', ' ').split()[1]
        except AttributeError:
            card['preco'] = 0
        
        #preco com desconto
        try:
            card['preco_desconto'] = anuncio.find('p', class_="sc-hKgJUU kegCEa sc-bxnjHY cTpdOW").getText().replace('\xa0', ' ').split()[1]
        except AttributeError:
            card['preco_desconto'] = 0
            
        #capiturando o preco parcelaado
        try:
            value = anuncio.find('div', class_="sc-jSgvzq fdbhJo sc-kGNyvp kBUBND").findAll('p')[2].getText().split()[1:5:3]   
            card['parcelas'] = value[0].split('x')[0]
            card['valor_parcela'] = value[1]
        except IndexError:
            card['parcelas'] = 1
            card['valor_parcela'] = card['preco_desconto']
        except AttributeError:
            card['parcelas'] = "0"
            card['valor_parcela'] = 0

        #Adicionando resultado a lista cards
        cards.append(card)
    
#Criando um dataframe com os resultados
dataset = pd.DataFrame(cards)
dataset.to_csv('./Geladeiras_magalu.csv', sep=';', index = False, encoding = 'utf-8-sig')
dataset

,Geladeira,preco,preco_desconto,parcelas,valor_parcela
0,Geladeira/Refrigerador Consul Frost Free Duplex,"4.099,00","3.399,00",10,"339,90"
1,Geladeira/Refrigerador Brastemp Frost Free Inv...,"6.300,00","4.399,00",10,"439,90"
2,Geladeira/Refrigerador Brastemp Frost Free Duplex,"4.270,00","3.099,00",10,"309,90"
3,Geladeira/Refrigerador Electrolux Frost Free,"4.340,00","2.499,00",10,"249,90"
4,Geladeira/Refrigerador Frost Free cor Inox 310...,"3.389,00","2.324,07",12,"208,25"
...,...,...,...,...,...
713,GeladeiraRefrigerador Electrolux Frost Free In...,"3.939,90","3.196,05",10,"343,66"
714,Refrigerador/geladeira bre57 akbna 2 pts 443 l...,"4.999,00","4.749,05",10,"499,90"
715,Geladeira Consul 450 Litros Frost Free Duplex ...,"3.699,00","3.699,00",1,"3.699,00"
716,Refrigerador French Door 579l Dm84x Electrolux,"8.190,00","7.780,50",1,"7.780,50"
717,Refrigerador Side Inverse Brastemp de 03 Porta...,0,0,0,0

# Categoria - Notebook Gamer

In [72]:
#declarando variáveis cards
cards = []

for i in (1, 2, 3, 4, 5, 6):
    time.sleep(10)
    url = 'https://www.magazineluiza.com.br/busca/notebook+gamer/?page=' + str(i) + '&sortOrientation=desc&sortType=soldQuantity'
    headers = {'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.81 Safari/537.36'}
    response = requests.get(url, headers = headers)
    soup = BeautifulSoup(response.content, "html.parser")

    anuncios = soup.find('ul', class_="sc-iktFfs ekIdSn sc-irlQje gbimYp sc-fBxREx fjFlfr").findAll('li', class_="sc-eCVOVf loRbcV")
    
    #Obtendo as informações dos cards
    for anuncio in anuncios:
        card = {}

        #nome da geladeira
        nome = anuncio.find('h2', class_="sc-bHXGc hsFKpx")
        card['Notebook'] = nome.getText()

        #preco da geladeira
        try:
            card['preco'] = anuncio.find('p').getText().replace('\xa0', ' ').split()[1]
        except AttributeError:
            card['preco'] = 0

        #preco com desconto
        try:
            card['preco_desconto'] = anuncio.find('p', class_="sc-hKgJUU kegCEa sc-bxnjHY cTpdOW").getText().replace('\xa0', ' ').split()[1]
        except AttributeError:
            card['preco_desconto'] = 0
            
        #capiturando o preco parcelaado
        try:
            value = anuncio.find('div', class_="sc-jSgvzq fdbhJo sc-kGNyvp kBUBND").findAll('p')[2].getText().split()[1:5:3]   
            card['parcelas'] = value[0].split('x')[0]
            card['valor_parcela'] = value[1]
        except IndexError:
            card['parcelas'] = 1
            card['valor_parcela'] = card['preco_desconto']
        except AttributeError:
            card['parcelas'] = "0"
            card['valor_parcela'] = 0

        #Adicionando resultado a lista cards
        cards.append(card)
    
#Criando um dataframe com os resultados
dataset = pd.DataFrame(cards)
dataset.to_csv('./Notebooks_magalu.csv', sep=';', index = False, encoding = 'utf-8-sig')
dataset

,Notebook,preco,preco_desconto,parcelas,valor_parcela
0,Notebook Gamer Acer Nitro 5 AN515-54-58CL Intel,"6.499,00","5.399,10",12,"499,92"
1,Notebook Gamer Acer Nitro 5 AN515-54-574Q Inte...,"6.999,00","5.224,05",12,"458,25"
2,Notebook 2AM E550 CI716256GBW10 Intel Core i7 ...,"9.999,00","5.849,10",12,"541,58"
3,Notebook Gamer Acer Nitro 5 AN515-43-R59W AMD R5,"6.499,00","5.399,10",12,"499,92"
4,Notebook Gamer Predator Helios 300 PH315-53-75...,"8.999,00","8.549,05",12,"749,92"
...,...,...,...,...,...
355,Asus GX701GW (Laptop Gamer) i7-9750H tela 17' ...,0,0,0,0
356,MSI Stealth 15M (Laptop Gamer) Intel 11ª gera...,0,0,0,0
357,"Notebook 15,6pol Dell Gaming G3 3590-U20P (Cor...",0,0,0,0
358,PC Gamer Intel 9ª Geração i7 9700K 4.9Ghz 8 Nú...,0,0,0,0
359,Notebook Gamer Asus F570ZD-DM387T Ryzen 5,0,0,0,0

# Fazendo testes de leitura dos arquivos

In [73]:
MagaluLivros = pd.read_csv('./livros_magalu.csv', sep=';')

In [139]:
MagaluLivros.sort_values(by = 'preco', ascending = False)

,Livro,preco,preco_desconto,parcelas,valor_parcela
1,BOX HARRY POTTER EDIÇÃO COMEMORATIVA 20 ANOS ...,499.90,237.41,12,20.83
514,Kit Livros Box Harry Potter + Livro,429.80,209.67,12,18.39
319,Box Duna: segunda trilogia,259.90,233.91,4,58.48
2,Box Trilogia O Senhor dos Anéis,199.90,98.00,6,16.33
35,Harry Potter e o cálice de fogo - EDIÇÃO ILUS...,189.90,93.86,6,16.47
...,...,...,...,...,...
633,O retorno de Arsène Lupin,11.26,10.13,1,10.13
523,Os bilhões de Arsène Lupin,10.82,9.74,1,9.74
707,Faca na Garganta,9.90,8.91,1,8.91
246,O Pequeno Príncipe,9.61,8.65,1,8.65
468,O Pequeno Príncipe,8.90,8.01,1,8.01

### Função para tratar ps preços com virgulas

In [145]:
def tratamento_virgula_ponto(dataset, colun):
    for i in range(dataset.shape[0]):
        dataset.loc[i, colun] = dataset.loc[i, colun].replace('.', '')
        dataset.loc[i, colun] = dataset.loc[i, colun].replace(',', '.')  
    return dataset.astype({ colun : float})

In [141]:
MagaluGeladeiras = pd.read_csv('./Geladeiras_magalu.csv', sep=';')
MagaluGeladeiras

,Geladeira,preco,preco_desconto,parcelas,valor_parcela
0,Geladeira/Refrigerador Consul Frost Free Duplex,"4.099,00","3.399,00",10,"339,90"
1,Geladeira/Refrigerador Brastemp Frost Free Inv...,"6.300,00","4.399,00",10,"439,90"
2,Geladeira/Refrigerador Brastemp Frost Free Duplex,"4.270,00","3.099,00",10,"309,90"
3,Geladeira/Refrigerador Electrolux Frost Free,"4.340,00","2.499,00",10,"249,90"
4,Geladeira/Refrigerador Frost Free cor Inox 310...,"3.389,00","2.324,07",12,"208,25"
...,...,...,...,...,...
713,GeladeiraRefrigerador Electrolux Frost Free In...,"3.939,90","3.196,05",10,"343,66"
714,Refrigerador/geladeira bre57 akbna 2 pts 443 l...,"4.999,00","4.749,05",10,"499,90"
715,Geladeira Consul 450 Litros Frost Free Duplex ...,"3.699,00","3.699,00",1,"3.699,00"
716,Refrigerador French Door 579l Dm84x Electrolux,"8.190,00","7.780,50",1,"7.780,50"
717,Refrigerador Side Inverse Brastemp de 03 Porta...,0,0,0,0